[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/capi"
  to   = "/.netlify/functions/capi"
  status = 200